version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: mubi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112358
    ports:
      - "5432:5432"


  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

    env_file:
      - .env

volumes:
  postgres_data:
